server:
  port: 8761
spring:
  application:
    name: discovery-ws
  security:
    user:
      name: eureka
      password: eureka
  boot:
    admin:
      client:
        url:
        - http://localhost:8888
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka
  instance:
    prefer-ip-address: true